### ISSUE TITLE
XQuery functions failing when given an empty region list

### ISSUE THREAD

**Issue by pralitp** [JGCRI/rgcam#16]
An empty region list should indicate query all regions however the code to finalize they `XQuery` before running doesn't properly cope with this:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:729)
	at java.lang.StringBuilder.delete(StringBuilder.java:244)
	at ModelInterface.ModelGUI2.xmldb.RunFunctionQueryBinding.bindToQuery(RunFunctionQueryBinding.java:61)
	at ModelInterface.ModelGUI2.xmldb.XMLDB.createQuery(XMLDB.java:280)
```

**Comment by michaeljaywalsh** [comment]
I have the same issue
