### ISSUE TITLE
Error connecting to db

### ISSUE THREAD

**Issue by nrb177** [JGCRI/rgcam#61]
I am having problems with the conn/ localDBConn 
The file which is is trying to access is present. (but 0 KB)

> conn <- localDBConn('/~/Downloads/gcam-v5.1.3-Mac-Release-Package/output/', 'database_basexdb')
Error in localDBConn("/~/Downloads/gcam-v5.1.3-Mac-Release-Package/output/",  : 
  could not find function "localDBConn"

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/basex/BaseX : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Error in guess_header_(datasource, tokenizer, locale) : 
  Cannot read file /private/var/folders/w7/kl1z27s96qg0d0dl19p3s7800000gp/T/RtmpqKaiVa/file116ac6ba15832: Invalid argument
<img width="1100" alt="Screen Shot 2019-06-08 at 17 03 52" src="https://user-images.githubusercontent.com/11742511/59148949-7561d880-8a0f-11e9-95fc-ddd7ace45b88.png">

**Comment by rplzzz** [comment]
@pralitp This line makes it look like there is a problem with the Java config:
> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/basex/BaseX : Unsupported major.minor version 52.0
What do you think?

**Comment by pralitp** [comment]
That error message indicates you are using older version of Java than is currently supported.  `rgcam` currently requires (due to the `BaseX` XML database library) Java 1.8+
